# Chart Releaser configuration
# https://github.com/helm/chart-releaser

owner: hypershield-se
git-repo: charts
charts-repo-url: https://hypershield-se.github.io/charts
git-base-url: https://api.github.com/

# Release name template (uses semantic versioning from Chart.yaml)
release-name-template: "{{ .Name }}-{{ .Version }}"

# Generate release notes from Git commits
generate-release-notes: true

# Store packaged charts in this directory (on gh-pages branch)
packages-with-index: true

# Sign packages (optional - requires GPG key)
sign: false

# Mark releases as latest
make-release-latest: true

# Skip existing releases
skip-existing: true
