{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.fluentbit.enabled .Values.fluentbit.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tetragon-observability-stack.fullname" . }}-fluentbit
  namespace: {{ include "tetragon-observability-stack.namespace" . }}
  labels:
    {{- include "tetragon-observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: fluent-bit
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: fluentbit
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow Prometheus to scrape metrics
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 2020
  egress:
  # Allow egress to OTel Collector Agent
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: otelAgent
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 4317
  # Allow DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
  {{- if .Values.networkPolicies.fluentbit.allowKubeAPIAccess }}
  # Allow access to Kubernetes API for metadata enrichment
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    ports:
    - protocol: TCP
      port: 443
  {{- end }}
{{- end }}
