{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.tetragon.enabled .Values.tetragon.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tetragon-observability-stack.fullname" . }}-tetragon
  namespace: {{ include "tetragon-observability-stack.namespace" . }}
  labels:
    {{- include "tetragon-observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: tetragon
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tetragon
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow Prometheus to scrape metrics
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 2112
  # Allow internal gRPC communication
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 54321
  egress:
  {{- if .Values.networkPolicies.tetragon.allowKubeAPIAccess }}
  # Allow access to Kubernetes API for metadata enrichment
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    ports:
    - protocol: TCP
      port: 443
  {{- end }}
  # Allow DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
  # Allow egress to policy server (for fetching policies)
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "tetragon-observability-stack.name" . }}-policy-server
          app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 80
{{- end }}
