{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitors.otelAgent.enabled .Values.otelAgent.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tetragon-observability-stack.fullname" . }}-otelagent
  namespace: {{ include "tetragon-observability-stack.namespace" . }}
  labels:
    {{- include "tetragon-observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-agent
    {{- with .Values.monitoring.serviceMonitors.otelAgent.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otelAgent
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: agent-collector
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitors.otelAgent.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitors.otelAgent.scrapeTimeout }}
    path: /metrics
    scheme: http
    {{- with .Values.monitoring.serviceMonitors.otelAgent.relabelings }}
    relabelings:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.monitoring.serviceMonitors.otelAgent.metricRelabelings }}
    metricRelabelings:
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
